name: nim CI

on:
  push:
    paths:
      - 'pnimrp.nim'
      - 'src/**'
  pull_request:

    paths:
      - 'pnimrp.nim'
      - 'src/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Nim
        run: |
          sudo apt-get update
          sudo apt-get install -y nim

      - name: Build the project
        run: nim c pnimrp.nim
